/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintOpItemIdRouteImport } from './routes/print-op.$itemId'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppProducaoRouteImport } from './routes/_app/producao'
import { Route as AppPedidosCompraRouteImport } from './routes/_app/pedidos-compra'
import { Route as AppPedidosRouteImport } from './routes/_app/pedidos'
import { Route as AppOrcamentosRouteImport } from './routes/_app/orcamentos'
import { Route as AppMotorProdutosRouteImport } from './routes/_app/motor-produtos'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppHubFornecedoresRouteImport } from './routes/_app/hub-fornecedores'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustosRouteImport } from './routes/_app/custos'
import { Route as AppContratosRouteImport } from './routes/_app/contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppArquivosRouteImport } from './routes/_app/arquivos'
import { Route as AppProdutosImportarRouteImport } from './routes/_app/produtos_.importar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOpItemIdRoute = PrintOpItemIdRouteImport.update({
  id: '/print-op/$itemId',
  path: '/print-op/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosCompraRoute = AppPedidosCompraRouteImport.update({
  id: '/pedidos-compra',
  path: '/pedidos-compra',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMotorProdutosRoute = AppMotorProdutosRouteImport.update({
  id: '/motor-produtos',
  path: '/motor-produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppHubFornecedoresRoute = AppHubFornecedoresRouteImport.update({
  id: '/hub-fornecedores',
  path: '/hub-fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustosRoute = AppCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppArquivosRoute = AppArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosImportarRoute = AppProdutosImportarRouteImport.update({
  id: '/produtos_/importar',
  path: '/produtos/importar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AppArquivosRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/custos': typeof AppCustosRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/hub-fornecedores': typeof AppHubFornecedoresRoute
  '/leads': typeof AppLeadsRoute
  '/motor-produtos': typeof AppMotorProdutosRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pedidos': typeof AppPedidosRoute
  '/pedidos-compra': typeof AppPedidosCompraRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/print-op/$itemId': typeof PrintOpItemIdRoute
  '/produtos/importar': typeof AppProdutosImportarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/arquivos': typeof AppArquivosRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contratos': typeof AppContratosRoute
  '/custos': typeof AppCustosRoute
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/hub-fornecedores': typeof AppHubFornecedoresRoute
  '/leads': typeof AppLeadsRoute
  '/motor-produtos': typeof AppMotorProdutosRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pedidos': typeof AppPedidosRoute
  '/pedidos-compra': typeof AppPedidosCompraRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/print-op/$itemId': typeof PrintOpItemIdRoute
  '/produtos/importar': typeof AppProdutosImportarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/arquivos': typeof AppArquivosRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/custos': typeof AppCustosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/hub-fornecedores': typeof AppHubFornecedoresRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/motor-produtos': typeof AppMotorProdutosRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/pedidos-compra': typeof AppPedidosCompraRoute
  '/_app/producao': typeof AppProducaoRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/print-op/$itemId': typeof PrintOpItemIdRoute
  '/_app/produtos_/importar': typeof AppProdutosImportarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/custos'
    | '/dashboard'
    | '/financeiro'
    | '/hub-fornecedores'
    | '/leads'
    | '/motor-produtos'
    | '/orcamentos'
    | '/pedidos'
    | '/pedidos-compra'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/print-op/$itemId'
    | '/produtos/importar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/custos'
    | '/dashboard'
    | '/financeiro'
    | '/hub-fornecedores'
    | '/leads'
    | '/motor-produtos'
    | '/orcamentos'
    | '/pedidos'
    | '/pedidos-compra'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/print-op/$itemId'
    | '/produtos/importar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/arquivos'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/contratos'
    | '/_app/custos'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/hub-fornecedores'
    | '/_app/leads'
    | '/_app/motor-produtos'
    | '/_app/orcamentos'
    | '/_app/pedidos'
    | '/_app/pedidos-compra'
    | '/_app/producao'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/print-op/$itemId'
    | '/_app/produtos_/importar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  PrintOpItemIdRoute: typeof PrintOpItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-op/$itemId': {
      id: '/print-op/$itemId'
      path: '/print-op/$itemId'
      fullPath: '/print-op/$itemId'
      preLoaderRoute: typeof PrintOpItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos-compra': {
      id: '/_app/pedidos-compra'
      path: '/pedidos-compra'
      fullPath: '/pedidos-compra'
      preLoaderRoute: typeof AppPedidosCompraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motor-produtos': {
      id: '/_app/motor-produtos'
      path: '/motor-produtos'
      fullPath: '/motor-produtos'
      preLoaderRoute: typeof AppMotorProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hub-fornecedores': {
      id: '/_app/hub-fornecedores'
      path: '/hub-fornecedores'
      fullPath: '/hub-fornecedores'
      preLoaderRoute: typeof AppHubFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/custos': {
      id: '/_app/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AppCustosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arquivos': {
      id: '/_app/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AppArquivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos_/importar': {
      id: '/_app/produtos_/importar'
      path: '/produtos/importar'
      fullPath: '/produtos/importar'
      preLoaderRoute: typeof AppProdutosImportarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArquivosRoute: typeof AppArquivosRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCustosRoute: typeof AppCustosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppHubFornecedoresRoute: typeof AppHubFornecedoresRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMotorProdutosRoute: typeof AppMotorProdutosRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppPedidosCompraRoute: typeof AppPedidosCompraRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppProdutosImportarRoute: typeof AppProdutosImportarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArquivosRoute: AppArquivosRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppCustosRoute: AppCustosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppHubFornecedoresRoute: AppHubFornecedoresRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMotorProdutosRoute: AppMotorProdutosRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppPedidosCompraRoute: AppPedidosCompraRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppProdutosImportarRoute: AppProdutosImportarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  PrintOpItemIdRoute: PrintOpItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
